project_id = "zralumtepvrxvqewijtm"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[functions.fetch-economic-data]
verify_jwt = false