// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zralumtepvrxvqewijtm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpyYWx1bXRlcHZyeHZxZXdpanRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwMDk2MTEsImV4cCI6MjA3MTU4NTYxMX0.Kv8yEIE0TL6iziTo2KiSq-1Ly4eVe2_sSEPJZfki8Tg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});